### ISSUE TITLE
loading pkl ckpt issue.

### ISSUE THREAD

**Issue by javierztl** [adobe-research/layered-depth-refinement#1]
Thank you very much for your excellent work.

I met a problem loading ckpt from the pkl file you provide. 

`model = pickle.load(open(args.ckpt_path, 'rb'))`

`_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.`

My environment is set as you said.

**Comment by sooyekim** [comment]
Hi @javierztl, I replaced the .pkl checkpoint file to a .pth checkpoint. Could you verify if it's working now? Thanks!

**Comment by javierztl** [comment]
yes, it works, thank you.
