### ISSUE TITLE
Could you share your checkpoints?

### ISSUE THREAD

**Issue by yangtiming** [adobe-research/layered-depth-refinement#2]
Could you share your checkpoints?

ckpt/maskdepth_model.pth is 4.0K?

**Comment by sooyekim** [comment]
Hi @yangtiming, It's linked via git-lfs which currently has issues. Please understand that I cannot directly share model checkpoints. I'll update the status in #3

**Comment by sooyekim** [comment]
@yangtiming `git-lfs` issue has been resolved and you should be able to access the checkpoint when you clone the repo :smile:
