### ISSUE TITLE
Any chance you can upload checkpoint file?

### ISSUE THREAD

**Issue by MiriamFarber** [adobe-research/layered-depth-refinement#3]
I'm getting

`Error downloading object: ckpt/maskdepth_model.pth (a500b78): Smudge error: Error downloading ckpt/maskdepth_model.pth (a500b7897ee883d44f2f651e3dc2ba8de83bda5085877bf31fef30eefc3c0b2e): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

when trying to clone your repository

**Comment by sooyekim** [comment]
Hi @MiriamFarber, Thanks for reporting this issue! I've contacted the relevant people to get more data packs for the account. I'll let you know here when it's done. Please understand that I cannot directly share model checkpoints with you per company policy.

**Comment by sooyekim** [comment]
@MiriamFarber It should be working now. Could you please try cloning the repo again and let me know if it works? Thanks!

**Comment by MiriamFarber** [comment]
Yes that works, thanks!
